//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower_in_NCU.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tower_in_NCU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actor1 {
            get {
                object obj = ResourceManager.GetObject("Actor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap author {
            get {
                object obj = ResourceManager.GetObject("author", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream bgm {
            get {
                return ResourceManager.GetStream("bgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream cancel {
            get {
                return ResourceManager.GetStream("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream changeChoice {
            get {
                return ResourceManager.GetStream("changeChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap choiceBackground {
            get {
                object obj = ResourceManager.GetObject("choiceBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap choiceBackground2 {
            get {
                object obj = ResourceManager.GetObject("choiceBackground2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream confirm {
            get {
                return ResourceManager.GetStream("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap dialogueBackground {
            get {
                object obj = ResourceManager.GetObject("dialogueBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream door {
            get {
                return ResourceManager.GetStream("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap downArrow {
            get {
                object obj = ResourceManager.GetObject("downArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream eliminate {
            get {
                return ResourceManager.GetStream("eliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream enemyAttack {
            get {
                return ResourceManager.GetStream("enemyAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream fail {
            get {
                return ResourceManager.GetStream("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	3	0	0	75	80	75	0	1	3	85	80	1
        ///1	1	1	1	1	1	1	0	1	1	1	75	1
        ///1	0	90	85	80	75	15	0	16	90	1	15	1
        ///1	1	15	1	1	1	1	0	1	13	1	0	1
        ///1	5	105	5	1	90	15	0	1	12	1	0	1
        ///1	1	15	1	1	12	1	0	1	10	1	0	1
        ///1	13	105	12	1	1	1	0	1	1	1	0	1
        ///1	5	10	5	1	0	0	0	0	0	0	0	1
        ///1	1	15	1	1	1	0	1	1	1	16	1	1
        ///1	12	120	13	1	0	0	0	1	5	120	5	1
        ///1	6	10	5	1	0	0	0	1	5	5	5	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1
        /// 的當地語系化字串。
        /// </summary>
        internal static string floor1 {
            get {
                return ResourceManager.GetString("floor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	4	0	0	75	80	75	0	1	4	0	105	1
        ///1	1	1	1	1	1	1	0	1	1	1	20	1
        ///1	42	40	43	1	0	0	0	5	5	1	1	1
        ///1	12	0	13	15	0	1	1	1	1	1	12	1
        ///1	10	0	10	1	0	75	1	5	5	1	13	1
        ///1	1	1	1	1	0	80	15	120	13	1	85	1
        ///1	5	6	10	1	0	85	1	1	1	1	80	1
        ///1	5	0	90	15	0	80	15	105	5	1	75	1
        ///1	1	1	1	1	0	75	1	12	1	1	15	1
        ///1	5	6	10	1	0	0	1	1	1	5	0	1
        ///1	5	0	105	15	0	0	0	0	15	0	2	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1
        /// 的當地語系化字串。
        /// </summary>
        internal static string floor2 {
            get {
                return ResourceManager.GetString("floor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	3	0	0	0	15	0	75	80	13	1	7	1
        ///1	1	1	1	1	1	0	75	10	80	1	110	1
        ///1	25	1	10	5	1	0	75	10	85	1	120	1
        ///1	120	1	12	90	15	0	75	85	12	1	95	1
        ///1	105	1	13	5	1	15	1	1	1	1	105	1
        ///1	90	1	1	1	1	0	5	75	10	1	90	1
        ///1	85	80	75	16	15	0	0	0	75	1	85	1
        ///1	1	1	1	1	1	1	1	1	15	1	80	1
        ///1	0	0	0	0	80	85	80	10	0	16	75	1
        ///1	15	1	1	1	1	1	1	1	1	1	1	1
        ///1	0	0	0	10	75	85	75	12	13	0	4	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1
        /// 的當地語系化字串。
        /// </summary>
        internal static string floor3 {
            get {
                return ResourceManager.GetString("floor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	4	0	0	0	80	85	80	0	0	0	10	1
        ///1	1	1	1	1	1	1	1	1	1	1	15	1
        ///1	0	0	0	0	105	105	105	0	0	0	10	1
        ///1	0	1	1	1	1	1	1	1	1	1	1	1
        ///1	0	1	120	15	0	0	0	0	0	15	0	1
        ///1	0	1	5	1	0	1	1	1	0	1	95	1
        ///1	0	1	1	1	0	1	12	1	0	1	13	1
        ///1	0	0	0	15	0	1	95	15	0	1	12	1
        ///1	1	15	1	1	1	1	10	1	0	1	45	1
        ///1	0	120	0	1	6	1	1	1	0	1	1	1
        ///1	13	12	5	1	5	13	120	15	0	17	3	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1
        /// 的當地語系化字串。
        /// </summary>
        internal static string floor4 {
            get {
                return ResourceManager.GetString("floor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	1	1	1	1	1	145	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	0	0	0	0	0	0	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1 的當地語系化字串。
        /// </summary>
        internal static string floor5 {
            get {
                return ResourceManager.GetString("floor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap gameintro {
            get {
                object obj = ResourceManager.GetObject("gameintro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap gameOver {
            get {
                object obj = ResourceManager.GetObject("gameOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] gameover1 {
            get {
                object obj = ResourceManager.GetObject("gameover1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream getItem {
            get {
                return ResourceManager.GetStream("getItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap KeymanFace {
            get {
                object obj = ResourceManager.GetObject("KeymanFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap leftArrow {
            get {
                object obj = ResourceManager.GetObject("leftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap monstersintro {
            get {
                object obj = ResourceManager.GetObject("monstersintro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream move {
            get {
                return ResourceManager.GetStream("move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream playerAttack {
            get {
                return ResourceManager.GetStream("playerAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap rightArrow {
            get {
                object obj = ResourceManager.GetObject("rightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap slidebar {
            get {
                object obj = ResourceManager.GetObject("slidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap slidebarBackground {
            get {
                object obj = ResourceManager.GetObject("slidebarBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap story {
            get {
                object obj = ResourceManager.GetObject("story", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap thanks {
            get {
                object obj = ResourceManager.GetObject("thanks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap TonyFace {
            get {
                object obj = ResourceManager.GetObject("TonyFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap upArrow {
            get {
                object obj = ResourceManager.GetObject("upArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
