//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tower_in_NCU.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tower_in_NCU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actor1 {
            get {
                object obj = ResourceManager.GetObject("Actor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap author {
            get {
                object obj = ResourceManager.GetObject("author", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Cance {
            get {
                return ResourceManager.GetStream("Cance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ChoiceBackground {
            get {
                object obj = ResourceManager.GetObject("ChoiceBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ChoiceBackground2 {
            get {
                object obj = ResourceManager.GetObject("ChoiceBackground2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Confirm {
            get {
                return ResourceManager.GetStream("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap DialogueBackground {
            get {
                object obj = ResourceManager.GetObject("DialogueBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Eliminate {
            get {
                return ResourceManager.GetStream("Eliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream EnemyAttack {
            get {
                return ResourceManager.GetStream("EnemyAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Exploration {
            get {
                return ResourceManager.GetStream("Exploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Fail {
            get {
                return ResourceManager.GetStream("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	3	0	0	49	50	49	0	1	3	51	50	1
        ///1	1	1	1	1	1	1	0	1	1	1	49	1
        ///1	0	52	51	50	49	15	0	16	52	1	15	1
        ///1	1	15	1	1	1	1	0	1	13	1	0	1
        ///1	5	55	5	1	52	15	0	1	12	1	0	1
        ///1	1	15	1	1	12	1	0	1	10	1	0	1
        ///1	13	55	12	1	1	1	0	1	1	1	0	1
        ///1	5	10	5	1	0	0	0	0	0	0	0	1
        ///1	1	15	1	1	1	0	1	1	1	16	1	1
        ///1	12	58	13	1	0	0	0	1	5	58	5	1
        ///1	6	10	5	1	0	0	0	1	5	5	5	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1
        /// 的當地語系化字串。
        /// </summary>
        internal static string Floor1 {
            get {
                return ResourceManager.GetString("Floor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	4	0	0	49	50	49	0	1	4	0	55	1
        ///1	1	1	1	1	1	1	0	1	1	1	20	1
        ///1	41	40	42	1	0	0	0	5	5	1	1	1
        ///1	12	0	13	15	0	1	1	1	1	1	12	1
        ///1	10	0	10	1	0	49	1	5	5	1	13	1
        ///1	1	1	1	1	0	50	15	58	13	1	51	1
        ///1	5	6	10	1	0	51	1	1	1	1	50	1
        ///1	5	0	52	15	0	50	15	55	5	1	49	1
        ///1	1	1	1	1	0	49	1	12	1	1	15	1
        ///1	5	6	10	1	0	0	1	1	1	5	0	1
        ///1	5	0	55	15	0	0	0	0	15	0	2	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1
        /// 的當地語系化字串。
        /// </summary>
        internal static string Floor2 {
            get {
                return ResourceManager.GetString("Floor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	3	0	0	0	15	0	49	50	13	1	7	1
        ///1	1	1	1	1	1	0	49	10	50	1	56	1
        ///1	25	1	10	5	1	0	49	10	51	1	58	1
        ///1	58	1	12	52	15	0	49	51	12	1	53	1
        ///1	55	1	13	5	1	15	1	1	1	1	55	1
        ///1	52	1	1	1	1	0	5	49	10	1	52	1
        ///1	51	50	49	16	15	0	0	0	49	1	51	1
        ///1	1	1	1	1	1	1	1	1	15	1	50	1
        ///1	0	0	0	0	50	51	50	10	0	16	49	1
        ///1	15	1	1	1	1	1	1	1	1	1	1	1
        ///1	0	0	0	10	49	51	49	12	13	0	4	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1
        /// 的當地語系化字串。
        /// </summary>
        internal static string Floor3 {
            get {
                return ResourceManager.GetString("Floor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	4	0	0	0	50	51	50	0	0	0	10	1
        ///1	1	1	1	1	1	1	1	1	1	1	15	1
        ///1	0	0	0	0	55	55	55	0	0	0	10	1
        ///1	0	1	1	1	1	1	1	1	1	1	1	1
        ///1	0	1	58	15	0	0	0	0	0	15	0	1
        ///1	0	1	5	1	0	1	1	1	0	1	53	1
        ///1	0	1	1	1	0	1	12	1	0	1	13	1
        ///1	0	0	0	15	0	1	53	15	0	1	12	1
        ///1	1	15	1	1	1	1	10	1	0	1	45	1
        ///1	0	58	0	1	6	1	1	1	0	1	1	1
        ///1	13	12	5	1	5	13	58	15	0	17	3	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1
        /// 的當地語系化字串。
        /// </summary>
        internal static string Floor4 {
            get {
                return ResourceManager.GetString("Floor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1	1	1	1	1	1	1	1	1	1	1	1	1
        ///1	1	1	1	1	1	50	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	1	1	1	1	1	0	1	1	1	1	1	1
        ///1	0	0	0	0	0	0	0	0	0	0	0	1
        ///1	1	1	1	1	1	1	1	1	1	1	1	1 的當地語系化字串。
        /// </summary>
        internal static string Floor5 {
            get {
                return ResourceManager.GetString("Floor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Gameintro {
            get {
                object obj = ResourceManager.GetObject("Gameintro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap GameOver {
            get {
                object obj = ResourceManager.GetObject("GameOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] Gameover1 {
            get {
                object obj = ResourceManager.GetObject("Gameover1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream GetItem {
            get {
                return ResourceManager.GetStream("GetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Image {
            get {
                object obj = ResourceManager.GetObject("Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap KeymanFace {
            get {
                object obj = ResourceManager.GetObject("KeymanFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap monstersintro {
            get {
                object obj = ResourceManager.GetObject("monstersintro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Move {
            get {
                return ResourceManager.GetStream("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream OpenDoor {
            get {
                return ResourceManager.GetStream("OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PlayerAttack {
            get {
                return ResourceManager.GetStream("PlayerAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Select {
            get {
                return ResourceManager.GetStream("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Slidebar {
            get {
                object obj = ResourceManager.GetObject("Slidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap SlidebarBackground {
            get {
                object obj = ResourceManager.GetObject("SlidebarBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap story {
            get {
                object obj = ResourceManager.GetObject("story", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap thanks {
            get {
                object obj = ResourceManager.GetObject("thanks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap TonyFace {
            get {
                object obj = ResourceManager.GetObject("TonyFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap WownArrow {
            get {
                object obj = ResourceManager.GetObject("WownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
